### ISSUE TITLE
'maze' needs blancing

### ISSUE THREAD

**Issue by LetsCode-Angus** [TheLetsCodeProject/ProjectOrbis_2#21]
The maze 'maze.png' needs balancing. This is because as of current it is too easy to complete and it takes a full minute before the solver even has to make a decision. More gaps need to be made to break up the map more. It also needs a finish node.

**Comment by yaboipapasmurf** [comment]
there needs to be a few easy levels to get people hooked into the game, if I gave them the "God Maze" first up they'd probably get frustated and never come back to it.
